/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedAt' : bigint,
  'summary' : string,
  'category' : string,
}
export interface Guide {
  'id' : bigint,
  'title' : string,
  'description' : string,
}
export interface Tool {
  'id' : bigint,
  'link' : string,
  'name' : string,
  'description' : string,
}
export interface TopicCard {
  'id' : bigint,
  'title' : string,
  'description' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArticle' : ActorMethod<[string, string, string, string], undefined>,
  'addGuide' : ActorMethod<[string, string], undefined>,
  'addSubscriber' : ActorMethod<[string], string>,
  'addTool' : ActorMethod<[string, string, string], undefined>,
  'addTopicCard' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'deleteGuide' : ActorMethod<[bigint], undefined>,
  'deleteTool' : ActorMethod<[bigint], undefined>,
  'deleteTopicCard' : ActorMethod<[bigint], undefined>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGuides' : ActorMethod<[], Array<Guide>>,
  'getTools' : ActorMethod<[], Array<Tool>>,
  'getTopicCards' : ActorMethod<[], Array<TopicCard>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateArticle' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateGuide' : ActorMethod<[bigint, string, string], undefined>,
  'updateTool' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateTopicCard' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];