/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : IDL.Int,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Guide = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Tool = IDL.Record({
  'id' : IDL.Nat,
  'link' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const TopicCard = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addGuide' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addSubscriber' : IDL.Func([IDL.Text], [IDL.Text], []),
  'addTool' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addTopicCard' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteGuide' : IDL.Func([IDL.Nat], [], []),
  'deleteTool' : IDL.Func([IDL.Nat], [], []),
  'deleteTopicCard' : IDL.Func([IDL.Nat], [], []),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGuides' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
  'getTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getTopicCards' : IDL.Func([], [IDL.Vec(TopicCard)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateGuide' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateTool' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTopicCard' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : IDL.Int,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Guide = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Tool = IDL.Record({
    'id' : IDL.Nat,
    'link' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const TopicCard = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addGuide' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addSubscriber' : IDL.Func([IDL.Text], [IDL.Text], []),
    'addTool' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addTopicCard' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteGuide' : IDL.Func([IDL.Nat], [], []),
    'deleteTool' : IDL.Func([IDL.Nat], [], []),
    'deleteTopicCard' : IDL.Func([IDL.Nat], [], []),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGuides' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
    'getTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getTopicCards' : IDL.Func([], [IDL.Vec(TopicCard)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateGuide' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateTool' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTopicCard' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };